version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  
  fastapi:
    build: .  # 使用Dockerfile构建
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb  # 依赖mongodb服务启动